:sparkles: - REF-10 - New QRdecode on S3
Consoneo/barcode-qr-decoder-lambda pull request #1
Opened 2023-12-04 16:46 UTC by QuentinJost

2023-12-04 18:38 UTC, adorey requested changes
Quelques commentaires à discuter au besoins ;)

2023-12-04 18:38 UTC, adorey commented on README.md
> +   * `git clone https://github.com/Consoneo/Barcode-QR-Decoder-Lambda.git`
il y a pas de majuscule sur le repo Consoneo

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +                        data['entityLetter'] = data_list[2]
Et est-ce qu'on a vraiement besoin de l'updated datetime ?
utilise update aussi pour ajouter plusieurs valeur dans ton dictionnaire ça sera plus propre

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +            data['decoded'] = 0
Un peu moche ça tu ne pouvait pas le générer genre comme ça plutôt : data = { 'decodedAt': str_datetime_now }

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +            data['decoded'] = decoded
Met decoded dans ta boucle a true si nécessaire mais pas besoin de le remettre ici

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +            data['createdAt'] = str_datetime_now
Idem pour eux deux pourquoi ne pas les set au départ ?

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +            if True == decoded or key + 1 == len(images_from_path):
Tu set decoded a 1 et tu vérifie true c'est pas terribel

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +                }
On en fait quoi de la valeur de retour ? 
On peux la catcher où ?

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
> +    insert_df.to_sql(con=db, name='DocumentQrDecode', if_exists='append', index=False, method='multi')
A mon avis tu peux tout mettre sur une ligne
De plus le nom de la met le dans une const ou oen parametre de ta fonction ça sera plus modulable

2023-12-04 18:38 UTC, adorey commented on src/code/lambda_function.py
Ajoute un peu de commentaires sur tes fonctions

2023-12-05 09:12 UTC, QuentinJost commented on src/code/lambda_function.py
> +                }
Les retours permettent d'émettre des logs

2023-12-13 15:46 UTC, adorey approved these changes
Voir commentaire

2023-12-13 15:46 UTC, adorey commented on src/code/lambda_function.py
> +        # logger.info(f'## Huston we got a trouble: {str(e)}')
😄

2023-12-13 15:46 UTC, adorey commented on src/code/setup.sh
> +# zip -r lambda_function.zip Barcode-QR-Decoder-Lambda/src/code/lambda_function.py
Si pas utile dégage le

2024-04-03 22:01 UTC, merged